name = "1drive"
type = "webpack"
workers_dev = true
account_id = "67fa786883ece27a3711aab29491f4d8"
zone_id = "b04152d2c33ff4653cec1a579be6d42a"
kv_namespaces = [
    { binding = "BUCKET", id = "be407da39aa54d2f89a15d0f33841472" }
]

[env.staging]
name = "drive-staging"
